version: '1'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "And12345"  # Change this password to a secure one
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - my_network
  
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"  # AMQP port
      - "8081:15672"  # RabbitMQ Management UI
    networks:
      - my_network

networks:
  my_network:
    driver: bridge