// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PDFExtractionServiceWorker.Database;

#nullable disable

namespace PDFExtractionServiceWorker.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230904193315_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModelsLib.DatabaseModels.CategoriClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoriText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indsats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InstitutionReportCriterieaDatabasemodelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionReportCriterieaDatabasemodelId");

                    b.ToTable("CategoriClass");
                });

            modelBuilder.Entity("ModelsLib.DatabaseModels.InstitutionReportCriterieaDatabasemodel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("InstitutionReportCriterieaDatabasemodel");
                });

            modelBuilder.Entity("ModelsLib.DatabaseModels.CategoriClass", b =>
                {
                    b.HasOne("ModelsLib.DatabaseModels.InstitutionReportCriterieaDatabasemodel", null)
                        .WithMany("Categories")
                        .HasForeignKey("InstitutionReportCriterieaDatabasemodelId");
                });

            modelBuilder.Entity("ModelsLib.DatabaseModels.InstitutionReportCriterieaDatabasemodel", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
